### ISSUE TITLE
dev gone?

### ISSUE THREAD

**Issue by tghoward** [openaps/openaps-contrib#4]
dev branch seems to be dropped. Scott's install script points to dev so that part of the script fails. If dev is gone for good, I'll offer a fix to the script.

**Comment by tghoward** [comment]
this is the install script I'm referring to:

https://raw.githubusercontent.com/openaps/docs/master/scripts/quick-src.sh

**Comment by tghoward** [comment]
went ahead and pushed the fix to the script

**Comment by bewest** [comment]
Thanks.  Actually, all those commands should probably be changed to use `pip`:

`pip install git+git://github.com/openaps/openaps.git@dev` should install dev branch of openaps.

**Comment by tghoward** [comment]
Very slick. But it doesn't look like pip actually sets up a repository locally .. it just installs the dev version then cleans up and deletes the clone it downloaded. I believe the intention of the script is to give local access to the repositories.
